# Generated by Django 4.1.1 on 2022-11-20 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'permissions': (('can_delete_category', 'Может удалять категории'), ('can_create_category', 'Может добавлять категории'))},
        ),
    ]
