# Generated by Django 4.1.1 on 2022-11-20 08:01

import design.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['time_create'], 'permissions': (('can_change_status', 'Менять статус заявки'),)},
        ),
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='order',
            name='photo_design',
            field=models.ImageField(blank=True, max_length=254, upload_to=design.models.get_name_file, verbose_name='Фото'),
        ),
    ]
